### ISSUE TITLE
感谢集成，bug、建议和问题来了

### ISSUE THREAD

**Issue by yuyuye84** [cheny95/qweather#1]
大佬，试用了两天，感谢集成。

刚好遇到一个问题，来报告一下：
今天实体state显示为：“weather-night-partly-cloudy”，虽然在condition.py里看到了条目，但显示英文，且icon也没显示。

接着提两个建议：
1. aqi和生活指数能否写成list和dict，不要用字符串连起来，不便于templating。
2. 能否添加分钟级降水和天气预警接口，刚需~

最后提个问题：
我查了下昨天的大半天的访问量（我是昨天上午安装的），接近8k次挺高的。请问下轮询频次可以修改吗？

**Comment by cheny95** [comment]
请在此处下载新版本 https://github.com/cheny95/qweather/releases/tag/0.03

我理解错了你的意思，没有去看格点天气预报，给做了个小时级别的天气预报。可以在开发者工具-状态里看到

主要是因为我也不会python，平常也没时间，群里有朋友需要就现学的。。。

关于请求次数，你看一下最新的readme，我做了解释。https://github.com/cheny95/qweather#readme

AQI已经拆分出来了，方便你用模板调用。也可以在开发者工具-状态里看到

但是生活指数拿到手的数据就是循环的，所以生活指数没办法去做拆分。不过可以做到具体请求哪一个生活指数的内容。（不计划支持）

格点预报和预警这个，我有时间再看下吧

**Comment by cheny95** [comment]
@yuyuye84 新版本支持格点天气的分钟级预报与灾害预警。[点这里下载最新版，注意查看ReadMe。](https://github.com/cheny95/qweather/releases/tag/0.04)
