### ISSUE TITLE
能不能配置成ui添加啊

### ISSUE THREAD

**Issue by jiumoshou** [cheny95/qweather#10]
能不能配置成通过 配置->设备与服务->集成->添加集成 ui添加和 设置啊
![Uploading image.png…]()

**Comment by cheny95** [comment]
请使用“船新版本”的天气插件，无需注册开发者，兼容彩云天气卡片。

https://github.com/hasscc/tianqi

**Comment by jiumoshou** [comment]
需要设置服务器域，不知道是啥

**Comment by cheny95** [comment]
> 需要设置服务器域，不知道是啥

weather.com.cn
