### ISSUE TITLE
脚本位置正确，添加配置后，无法重启

### ISSUE THREAD

**Issue by murazi** [cheny95/qweather#11]
重新启动 Home Assistant 失败
The system cannot restart because the configuration is not valid: Platform error weather.qweather - Integration 'qweather' not found.

**Comment by cheny95** [comment]
一般是集成放入文件夹后，先重启一次，然后再去配置，配置完再次重启。
另外，请参考这个issue #10，更换了新的集成，可以通过UI配置。
