### ISSUE TITLE
当预报为 weather-pouring 时，无天气图标

### ISSUE THREAD

**Issue by tty228** [cheny95/qweather#4]
![QQ截图20220824184351](https://user-images.githubusercontent.com/33397881/186399400-50af2f0a-8e04-422c-9dd4-82a32ce79b3d.png)

  - datetime: '2022-08-25'
    temperature: 34
    templow: 24
    condition: weather-pouring
    wind_bearing: 45
    wind_speed: 16
    precipitation: 12.6
    humidity: 94
    precipitation_probability: 94
    pressure: 987

另外，7天预报中没有 text 信息，只有英文的状态，不好联动音箱做天气预报，大佬有空可以加上吗

**Comment by cheny95** [comment]
https://github.com/cheny95/qweather/releases/tag/0.07  @tty228

**Comment by cheny95** [comment]
优先支持了中文文本，图标不知道官方是不是可以支持。
另外，你的面板是哪个，可以分享一下吗？回头我看看是不是能fork一下，研究一下配套。

**Comment by tty228** [comment]
你说的面板指的是 Lovelace 吗？
我用的官方默认的 https://www.home-assistant.io/dashboards/weather-forecast

另外7天预报的图标正常了，实时的没显示（如果 weather-pouring 翻译是 暴雨 的话）
![QQ截图20220825095559](https://user-images.githubusercontent.com/33397881/186556688-1464332a-0c07-44bf-a56e-c2e429b449b2.png)

**Comment by cheny95** [comment]
@tty228 

[v0.0.8](https://github.com/cheny95/qweather/releases/tag/0.08)

修复实时天气的取值还原为英文，但是在属性中增加了中文字段（condition_desc），因为官方仅支持少量天气图标和解释。（所有偶尔会有图标不对的情况）
官方文档：
https://www.home-assistant.io/integrations/weather/
